spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-tutorial?createDatabaseIfNotExist=true
    username: root
    password: mysql
  jpa:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true